### ISSUE TITLE
ChromDet segfaults w/o specific error message

### ISSUE THREAD

**Issue by ghost** [david-juan/ChromDet#1]
Hi,
I am trying to run a full analysis (i.e., the command line that you labelled as recommended) on 38 samples. Merging the bed files seems to work fine (?), though I get errors like the following:
```bash
Error: line number 408 of file <local_path>/tmp_2 has 5 fields, but 4 were expected.
```
ChromDet nevertheless proceeds. Last message I get is `Step 4: Writing fasta file...` and then
```bash
RUNNING - Step 1: Running <local_path>/S3det_v2.2.exe -i <local_path>/samples_collapsed_filtered.fa -o <local_path>/samples_collapsed_filtered.s3 -v
Segmentation fault
```
What I can tell you about the intermediate/output files:
1) `samples_collapsed.tab`: this file looks truncated to me, contains only a few hundred regions from the first chromosome
2) `samples_collapsed_filtered.fa`: contains only FASTA header lines, but no sequences
3) `samples_collapsed_filtered.tab`: file is empty except for header line

Best,
Peter

**Comment by asalhab** [comment]
Hi @mpi-pebert 

I think the *bed files require to have only 4 columns. I tried ChromDet with such bed files and worked for me. It could be the problem.

Best,
Abdul

**Comment by ghost** [comment]
Hi @asalhab,
didn't know you were doing the support around here :-)
Thanks for the hint, this seems at least to get rid of the error during the initial processing of the bed files, but I still end up with a segfault
Can you tell me how many samples you are processing and whether or not the fasta and the samples_filtered.tab file are supposed to be empty or not? Thanks.

+Peter

**Comment by asalhab** [comment]
Hi @mpi-pebert 
happy to help :)
It just happened that I'm recently in contact with the developer and they mentioned me their new published tool and I have been using it since almost 10 days :)
I tested it with 12 samples after the last commit (~8days ago) since I had an error before, and I also added the path of S3det_Wilcoxon_test.R in conf.h file.
The fasta and samples_filtered.tab should not be empty. I will send you a mail with the local files I used (produced by your pipeline :) )
I'm not sure if "chr" in the chromosome name matters or not but I prepared the files with "chr"

Abdul

**Comment by ghost** [comment]
@asalhab 
ChromDet has been running w/o error message for quite a while now; so, apparently, it needs "chr" prefixed chromosome names - thanks again, Abdul.
I keep this issue open until it is finished.

**Comment by ecarrillo23** [comment]
Hi @mpi-pebert<https://github.com/mpi-pebert> and @asalhab<https://github.com/asalhab>,

Firstly, sorry about our delay we were out the last week and thanks @asalhab<https://github.com/asalhab> for your advices.

Please @mpi-pebert<https://github.com/mpi-pebert>, let us know if you had any issue after include the "chr" prefix for the chromosomes.

Best,

enrique



Enrique Carrillo de Santa Pau, PhD.
Spanish National Cancer Research Center, CNIO
Melchor Fernandez Almagro, 3.
28029 Madrid, Spain.
Phone: +34 91 224 6900 ext. 3019
ecarrillo@cnio.es<mailto:drico@cnio.es>

http://www.cnio.es
________________________________

**Comment by ghost** [comment]
@ecarrillo23 
Thanks for the feedback - the computation finished seemingly w/o any further errors (just took a couple of days). I am closing this issue, then.
