### ISSUE TITLE
Hard-coded tmp files in prepare_S3det_analysis

### ISSUE THREAD

**Issue by ghost** [david-juan/ChromDet#2]
Hi,
I just tried to run ChromDet on different subsets of the same dataset, i.e., one folder of input BED files and each run has a different sample annotation table.
The runs fail with a segfault, and I don't get any other helpful error message - I see, though, that the prepare_S3det_analysis.pl script seems to use hard-coded names for temp files (tmp_1, tmp_2 etc.) that are created in the input folder. I would now assume that runs in parallel interfere with each other due to that design decision. I think it would be quite important to update ChromDet's documentation and make it clear that each run should use its own (input) folder.
Best,
Peter

**Comment by david-juan** [comment]
Hi @mpi-pebert,

Thanks for pointing this out.

I have modified prepare_S3det_analysis.pl to prevent this problem in parallel runs.
I hope this will solve your problem,

Best,

David

**Comment by ghost** [comment]
Hi @david-juan ,
I solved it as described by resorting to separate input folders, but I will update my version of ChromDet asap. Thanks for fixing.
Best,
Peter
